name: Run Unit Tests on Aditional Branches

on:
  push:
    branches:
      - "**" # including all branches before excluding master
      - "!master"
      - "!main"

jobs:
  test-all:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.x"]
    steps:
      - uses: actions/checkout@master

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install poetry
        run: |  
          python -m pip install --upgrade pip setuptools wheel
          python -m pip install poetry

      - name: Install poetry dependencies
        run: |  
          python -m poetry update --with test

      - name: Run tests
        run: |  
          python -m poetry run coverage run --omit=./tests/* --source=./ddcLogs -m pytest -v

      - name: Generate Coverage Report
        run: |  
          python -m poetry run coverage report
